# Generated by Django 4.2.6 on 2024-04-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_camps', '0003_carrinhoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinhoitem',
            name='tamanho',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
