# Generated by Django 4.2.6 on 2024-04-14 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_camps', '0004_carrinhoitem_tamanho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinhoitem',
            name='tamanho',
            field=models.CharField(max_length=10),
        ),
    ]
